using HelloWorldEnterpriseEdition.Implementation;
using HelloWorldEnterpriseEdition.Interfaces;

// Create new instance of HelloWorldStringWriterProviderImplementationFactory
IStringWriterProviderImplementationFactory stringWriterProviderImplementationFactory = new HelloWorldStringWriterProviderImplementationFactory();

// Get HelloWorldStringWriterProviderImplementation instance from HelloWorldStringWriterProviderImplementationFactory
StringWriterProviderImplementation stringWriterProviderImplementation = stringWriterProviderImplementationFactory.Create();

// Execute HelloWorldStringWriterProviderImplementation
stringWriterProviderImplementation.Execute();